User mac to match nic

diff --git a/config/hostagent/jobs.yaml b/config/hostagent/jobs.yaml
--- a/config/hostagent/jobs.yaml
+++ b/config/hostagent/jobs.yaml
@@ -69,48 +69,78 @@ data:
     - name: Set network device configuration
       hosts: all
       become: true
-      gather_facts: false
+      vars:
+        mac_types: {}
       tasks:
       - name: Set network configuration for unconfigured nics
         shell: |
           set -e
+          shopt -s nullglob
 
-          echo "get list of ens/enp nics"
-          all_nics=($(ls /sys/class/net | grep -E '^(ens[0-9]+|enp[0-9]+s[0-9]+)$'))
+          declare -A mac_type_map
+          mac_type_map=(
+          {% for mac, type in mac_types.items() %}
+            ["{{ mac }}"]="{{ type }}"
+          {% endfor %}
+          )
 
-          echo "classify nics as unconfigured and static-configured"
-          unconfigured_nics=()
-          static_configured_nics=()
-          for nic in "${all_nics[@]}"; do
-            if ! ls /etc/sysconfig/network-scripts/ifcfg-$nic* 1>/dev/null 2>&1; then
-              unconfigured_nics+=("$nic")
-            else
-              if ls /etc/sysconfig/network-scripts/ifcfg-$nic-staticX 1>/dev/null 2>&1; then
-                static_configured_nics+=("$nic")
+          echo "Find NICs for MACs"
+
+          declare -A mac_nic_map
+          for i in /sys/class/net/{enp*,ens*}/address; do
+            nic=$(basename $(dirname "$i"))
+            mac=$(cat "$i")
+            mac_nic_map["$mac"]="$nic"
+          done
+
+          declare -A nic_type_map
+          for mac in "${!mac_type_map[@]}"; do
+            nic="${mac_nic_map[$mac]}"
+            if [[ -z "$nic" ]]; then
+              echo "Error: No NIC found for MAC $mac"
+              exit 1
+            fi
+
+            echo "Find NIC for MAC: $mac, Type: ${mac_type_map[$mac]}, NIC: $nic"
+
+            nic_type_map["$nic"]="${mac_type_map[$mac]}"
+          done
+
+          for nic in "${!nic_type_map[@]}"; do
+            echo "Set network configuration for NIC: $nic, Type: ${nic_type_map[$nic]}"
+
+            if [[ "${nic_type_map[$nic]}" == "NONE" || "${nic_type_map[$nic]}" == "IPV4_DHCP" ]]; then
+              if result=$(nmcli connection delete "$nic" 2>&1); then
+                echo "$result"
+              elif ! echo "$result" | grep -q "unknown connection"; then
+                echo "Error: failed to delete connection for $nic: $result"
+                exit 1
               fi
+            fi
+
+            if [ "${nic_type_map[$nic]}" == "NONE" ]; then
+              nmcli connection add type ethernet con-name "$nic" \
+                ifname "$nic" \
+                ipv4.method disabled \
+                ipv6.method ignore
+            elif [ "${nic_type_map[$nic]}" == "IPV4" ]; then
+              con_name=$(nmcli -g GENERAL.CONNECTION device show "$nic")
+              nmcli connection modify "$con_name" \
+                ipv4.never-default yes \
+                ipv6.never-default yes \
+                ipv4.ignore-auto-dns yes \
+                ipv6.ignore-auto-dns yes
+            elif [ "${nic_type_map[$nic]}" == "IPV4_DHCP" ]; then
+              nmcli connection add type ethernet con-name "$nic" \
+                ifname "$nic" \
+                ipv4.never-default yes \
+                ipv6.never-default yes \
+                ipv4.ignore-auto-dns yes \
+                ipv6.ignore-auto-dns yes
+            else
+              echo "Error: Unknown NIC type ${nic_type_map[$nic]}"
+              exit 1
             fi
           done
 
-          for nic in "${unconfigured_nics[@]}"; do
-            echo "set network configuration for nic $nic"
-            nmcli device connect $nic
-            connection_name=$(nmcli -g GENERAL.CONNECTION device show "$nic")
-            nmcli connection modify "$connection_name" ipv4.never-default yes ipv6.never-default yes ipv4.ignore-auto-dns yes ipv6.ignore-auto-dns yes
-            nmcli conn up "$connection_name"
-          done
-
-          if [ ${#unconfigured_nics[@]} -gt 0 ]; then
-            echo "set network configuration for unconfigured nics done"
-          fi
-
-          for nic in "${static_configured_nics[@]}"; do
-            echo "set default network configuration for nic $nic"
-            connection_name=$(nmcli -g GENERAL.CONNECTION device show "$nic")
-            nmcli connection modify "$connection_name" ipv4.never-default yes ipv6.never-default yes ipv4.ignore-auto-dns yes ipv6.ignore-auto-dns yes
-          done
-
-          if [ ${#static_configured_nics[@]} -gt 0 ]; then
-            echo "set default network configuration for static-configured nics done"
-          fi
-
-          echo "set network configuration for nics done"
+          echo "Set network configuration for nics done"
